TestComplex Class Reference
Public Member Functions
void input ()
string compare ()
Complex compute ()
Public Attributes
Complex a
Complex b
char operation
string result
Detailed Description
Definition at line 7 of file TestComplex.cpp.
Member Function Documentation
string TestComplex::compare ()
Definition at line 44 of file TestComplex.cpp.
Referenced by main().
Complex TestComplex::compute ()
Definition at line 51 of file TestComplex.cpp.
Referenced by main().
void TestComplex::input ()
Definition at line 19 of file TestComplex.cpp.
Referenced by main().
Member Data Documentation
Complex TestComplex::a
Definition at line 10 of file TestComplex.cpp.
Complex TestComplex::b
Definition at line 10 of file TestComplex.cpp.
char TestComplex::operation
Definition at line 11 of file TestComplex.cpp.
Referenced by main().
string TestComplex::result
Definition at line 12 of file TestComplex.cpp.
The documentation for this class was generated from the following file:
test/TestComplex.cpp