test/TestComplex.cpp File Reference
#include <iostream>
*
#include <string>
*
#include `complex.h`
*
Classes
class TestComplex
Functions
int main ()
Function Documentation
int main ()
Definition at line 61 of file TestComplex.cpp.
References TestComplex::compare(), TestComplex::compute(), TestComplex::input(), and TestComplex::operation.