include/complex.h File Reference
#include <iostream>
*
#include <cmath>
*
#include <string>
*
Classes
class Complex
Functions
Complex operator``_i (long double _i)
Complex operator``_i (unsigned long long _i)
Complex operator+ (Complex a, Complex b)
Complex operator- (Complex a, Complex b)
Complex operator* (Complex a, Complex b)
Complex operator/ (Complex a, Complex b)
Complex operator/ (Complex a, double b)
Complex operator- (Complex rhs)
bool operator== (Complex a, Complex b)
bool operator!= (Complex a, Complex b)
Complex conj (Complex rhs)
double arg (Complex rhs)
double real (Complex rhs)
double imag (Complex rhs)
double norm (Complex rhs)
double abs (Complex rhs)
Complex polar (double r, double t)
Complex exp (Complex rhs)
Complex log (Complex rhs)
Complex pow (double a, Complex b)
Complex pow (Complex a, double b)
Complex pow (Complex a, Complex b)
Complex sqrt (Complex rhs)
Complex root (Complex a, double b)
Complex sinh (Complex rhs)
Complex cosh (Complex rhs)
Complex sin (Complex rhs)
Complex cos (Complex rhs)
ostream & operator<< (ostream &os, Complex &c)
istream & operator>> (istream &is, Complex &c)
Function Documentation
double abs (Complex rhs)
Definition at line 260 of file complex.h.
References Complex::abs.
Referenced by operator<<(), and montecarlo::Pi_Estamtion().
double arg (Complex rhs)
Definition at line 217 of file complex.h.
References Complex::arg.
Complex conj (Complex rhs)
Definition at line 206 of file complex.h.
References Complex::i, and Complex::r.
Complex cos (Complex rhs)
Definition at line 327 of file complex.h.
References cosh().
Referenced by exp(), and polar().
Complex cosh (Complex rhs)
Definition at line 317 of file complex.h.
References exp().
Referenced by cos().
Complex exp (Complex rhs)
Definition at line 273 of file complex.h.
References cos(), Complex::i, Complex::r, and sin().
Referenced by cosh(), pow(), and sinh().
double imag (Complex rhs)
Definition at line 239 of file complex.h.
References Complex::i.
Complex log (Complex rhs)
Definition at line 279 of file complex.h.
References Complex::abs, and Complex::arg.
Referenced by pow().
double norm (Complex rhs)
Definition at line 250 of file complex.h.
References Complex::norm.
bool operator!= (Complex a, Complex b)
Definition at line 167 of file complex.h.
Complex operator``_i (long double _i)
Definition at line 94 of file complex.h.
Complex operator``_i (unsigned long long _i)
Definition at line 98 of file complex.h.
Complex operator* (Complex a, Complex b)
Definition at line 123 of file complex.h.
References Complex::i, and Complex::r.
Complex operator+ (Complex a, Complex b)
Definition at line 111 of file complex.h.
References Complex::i, and Complex::r.
Complex operator- (Complex a, Complex b)
Definition at line 117 of file complex.h.
References Complex::i, and Complex::r.
Complex operator- (Complex rhs)
Definition at line 154 of file complex.h.
References Complex::i, and Complex::r.
Complex operator/ (Complex a, Complex b)
Definition at line 129 of file complex.h.
References Complex::abs, and Complex::conj.
Complex operator/ (Complex a, double b)
Definition at line 136 of file complex.h.
References Complex::i, and Complex::r.
ostream& operator<< (ostream & os, Complex & c)
Definition at line 343 of file complex.h.
References abs(), Complex::i, and Complex::r.
bool operator== (Complex a, Complex b)
Definition at line 159 of file complex.h.
References Complex::i, and Complex::r.
istream& operator>> (istream & is, Complex & c)
Definition at line 353 of file complex.h.
References Complex::i, and Complex::r.
Complex polar (double r, double t)
Definition at line 267 of file complex.h.
References cos(), and sin().
Complex pow (double a, Complex b)
Definition at line 285 of file complex.h.
References exp(), and log().
Referenced by root(), and sqrt().
Complex pow (Complex a, double b)
Definition at line 290 of file complex.h.
References exp(), and log().
Complex pow (Complex a, Complex b)
Definition at line 295 of file complex.h.
References exp(), and log().
double real (Complex rhs)
Definition at line 228 of file complex.h.
References Complex::r.
Complex root (Complex a, double b)
Definition at line 306 of file complex.h.
References pow().
Complex sin (Complex rhs)
Definition at line 322 of file complex.h.
References sinh().
Referenced by exp(), and polar().
Complex sinh (Complex rhs)
Definition at line 312 of file complex.h.
References exp().
Referenced by sin().
Complex sqrt (Complex rhs)
Definition at line 301 of file complex.h.
References pow().
Referenced by Complex::abs().